/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b_Admin;

import config.config;
import javax.swing.JOptionPane;


/**
 *
 * @author juls
 */
public class staffform extends javax.swing.JFrame {

    /**
     * Creates new form customerform1
     */
    public staffform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSave = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 209, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DressRent__5_-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 130, 280, 200));

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel2.setText("Dress Rent");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 207, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("PREMIUM QUALITY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 32));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 240, 30));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 240, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel5.setText("ADD USER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 20));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel11.setText("FULL NAME:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel7.setText("EMAIL:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, 30));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel14.setText("PHONE:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, 30));

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel15.setText("ROLE/STATUS:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, 30));

        jLabel16.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel16.setText("STAFF ID:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 30));

        user_id.setEditable(false);
        user_id.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 102, 102)));
        jPanel1.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 240, 30));

        email.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 102, 102)));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 240, 30));

        name.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 102, 102)));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 240, 30));

        jTextField5.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jTextField5.setText("MM-DD-YYYY");
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 102, 102)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 170, 30));

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel17.setText("ADDRESS:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 30));

        role.setBackground(new java.awt.Color(255, 102, 102));
        role.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 90, 30));

        status.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Pending" }));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 100, 30));

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel18.setText("EMPLOYMENT DATE:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, 30));

        jPanel4.setBackground(new java.awt.Color(46, 139, 8));

        btnSave.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(240, 240, 240));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSave.setText("SAVE");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 110, 30));

        jPanel3.setBackground(new java.awt.Color(165, 42, 42));

        cancel.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        cancel.setForeground(new java.awt.Color(240, 240, 240));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("CANCEL");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked

        config conf = new config();

        // Check if we are UPDATING or SAVING NEW
        if (btnSave.getText().equals("UPDATE")) {
            String sql = "UPDATE Users SET full_name='" + name.getText() +
            "', email='" + email.getText() +
            "', number='" + number.getText() +
            "', address='" + address.getText() +
             "', password ='" + role.getSelectedItem() +  
            "', role ='" + role.getSelectedItem() +  
            "', status = '" + status.getSelectedItem()+        
            "' WHERE user_id='" + user_id.getText() + "'";
            conf.updateRecord(sql);
        } else {
           
    // 1. Added 'password' to the column list
    // 2. Added '1234' as the default value in the VALUES list
    String sql = "INSERT INTO Users (full_name, email, number, address, role, status, password) VALUES ('"
                + name.getText() + "', '"      
                + email.getText() + "', '"     
                + number.getText() + "', '"    
                + address.getText() + "', '"   
                + role.getSelectedItem() + "', '"           
                + status.getSelectedItem() + "', "
                + "'1234')"; // <--- Hardcoded default password
    
    conf.addRecord(sql);

        }

        JOptionPane.showMessageDialog(null, "Saved Successfully!");

        // REFRESH AND SHOW DASHBOARD
        for (java.awt.Frame frame : java.awt.Frame.getFrames()) {
            if (frame instanceof manageuser) {
                manageuser mu = (manageuser) frame;
                mu.displayUser();   // Make sure this is 'public' in manageuser.java
                mu.toFront();
                mu.requestFocus();
            }
        }

        this.dispose();
        }

        // --- PREPARE EDIT METHOD (Must be outside other methods) ---
      public void prepareEdit(String id, String nameVal, String mail, String num, String addr) {
    user_id.setText(id);
    name.setText(nameVal); // Use the 'name' JTextField, not user_id
    email.setText(mail);
    number.setText(num);
    address.setText(addr);

            // Disable the ID field so the user cannot change the Primary Key
            user_id.setEditable(false);

            // Change the button text so btnSave knows to UPDATE instead of INSERT
            btnSave.setText("UPDATE");


    }//GEN-LAST:event_btnSaveMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        manageuser manage = new manageuser();
        manage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel cancel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
